### ISSUE TITLE
importing the sdk causes a warning in webpack

### ISSUE THREAD

**Issue by jooohn** [contentful/ui-extensions-sdk#208] opened 2019-05-09 03:02 UTC
Maybe because of this parcel's issue (https://github.com/parcel-bundler/parcel/issues/2883), I've run into the same problem (https://github.com/jooohn/reproduce-contentful-ui-extensions-error).

I believe it's not originally this sdk's problem, but I want to know when the problem is fixed anyway!

**Comment by suevalov** [comment] 2019-05-09 11:38
@jooohn Thanks for creating a repo with a reproduced issue! 

What problems does this warning cause? From what I see at https://github.com/webpack/webpack/issues/196, it a long-running issue with Webpack and I'm not sure if we should act on it.

**Comment by jooohn** [comment] 2019-05-09 12:25
According to this issue, a library built with percel causes the warning when the built js is bundled with webpack.
https://github.com/parcel-bundler/parcel/issues/2883

I think it's an issue of either webpack or parcel, so possible approaches would be like this:

1. Wait for webpack fixes the issue.
2. Wait for parcel to fix the issue, and then build this SDK with the new version of parcel.
3. Build this SDK without parcel.

**Comment by andersrydman** [comment] 2019-12-17 16:19
Hi, 
I'm encountering the same issue when importing this into a create-react-app project. Are you aware of any way to fix it?

**Comment by fredski02** [comment] 2020-04-08 21:37
I get the same thing using webpack and vue.

**App.vue**
```js

import { init as initContentfulExtension } from 'contentful-ui-extensions-sdk'

export default {
  data () {
    return {
      extension: null
    }
  },
  created () {
    initContentfulExtension((extension) => {
      this.extension = extension
      this.extension.window.startAutoResizer()
    })
  }
}
```

**Comment by kamsar** [comment] 2020-08-25 21:35
This causes build failures on Netlify with apps created using the `create-contentful-app` utility, because it uses `create-react-app` (webpack) that treats warnings as errors during CI builds; https://github.com/contentful/create-contentful-app/issues/15

**Comment by Jwhiles** [comment] 2020-12-15 10:46
I believe this issue should be fixed in newer versions of the SDK, as we're no longer using parcel in this repo. Please feel free to open a new issue if this is still causing you problems.

**Closed by Jwhiles** 2020-12-15 10:46 UTC
